repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.12.0
  hooks:
  - id: pyupgrade
    exclude: docopt.py
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3.6
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
    additional_dependencies: ['flake8-bugbear==18.8.0; python_version >= "3.5"']
- repo: https://github.com/asottile/blacken-docs
  rev: v0.5.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]
